### ISSUE TITLE
pretrained model on Visual Genome

### ISSUE THREAD

**Issue by king-zark** [ruotianluo/bottom-up-attention-ai-challenger#2]
Hi, I use the code from another repository "pytorch-faster-rcnn" of you and employ the pretrained model on Mscoco dataset. The results seems not so good. I wanna if there is a pytorch-version pretrained model of faster-rcnn on Visual Genome? Thank you!

**Comment by ruotianluo** [comment]
Search fast-rcnn. Pytorch

**Comment by king-zark** [comment]
Thank you for that, but I searched the README in https://github.com/jwyang/faster-rcnn.pytorch, and there is no pre-trained model on Visual Genome. According to the editor jwyang, the pretrained model provided is trained on classification dataset? @ruotianluo

**Comment by ruotianluo** [comment]
Are you looking at http://data.lip6.fr/cadene/faster-rcnn.pytorch/faster_rcnn_1_19_48611.pth ?? If this is not, then I don't know.

**Comment by king-zark** [comment]
Thank you very much!!
